/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.iut;

import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;

/**
 *
 * @author roman
 */
public class DiffieHellmanGUI extends javax.swing.JFrame {

    /**
     * Creates new form DiffieHellmanGUI
     */
    public DiffieHellmanGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        alice = new javax.swing.JTextField();
        generateAlice = new javax.swing.JButton();
        labelB = new javax.swing.JLabel();
        bob = new javax.swing.JTextField();
        generateBob = new javax.swing.JButton();
        generateDFKey = new javax.swing.JButton();
        jScrollPane10 = new javax.swing.JScrollPane();
        DFKey = new javax.swing.JTextArea();
        copyDFKey = new javax.swing.JButton();

        setTitle("Diffie Hellman");

        jLabel11.setText("Saisissez a");

        generateAlice.setText("Ou générer a");
        generateAlice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateAliceActionPerformed(evt);
            }
        });

        labelB.setText("Saisissez b :");

        bob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bobActionPerformed(evt);
            }
        });

        generateBob.setText("Ou générer b");
        generateBob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateBobActionPerformed(evt);
            }
        });

        generateDFKey.setText("calculer Clé secrète");
        generateDFKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateDFKeyActionPerformed(evt);
            }
        });

        DFKey.setColumns(20);
        DFKey.setLineWrap(true);
        DFKey.setRows(5);
        DFKey.setName("texteCrypteRSA"); // NOI18N
        jScrollPane10.setViewportView(DFKey);

        copyDFKey.setText("Copier");
        copyDFKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyDFKeyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alice, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(generateDFKey)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(generateBob))
                            .addComponent(bob)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(generateAlice))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(copyDFKey)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(generateAlice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelB)
                    .addComponent(generateBob))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(generateDFKey)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(copyDFKey)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generateAliceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateAliceActionPerformed
        alice.setText(DiffieHellman.generateNumber());
    }//GEN-LAST:event_generateAliceActionPerformed

    private void bobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bobActionPerformed

    private void generateBobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateBobActionPerformed
        bob.setText(DiffieHellman.generateNumber());
    }//GEN-LAST:event_generateBobActionPerformed

    private void generateDFKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateDFKeyActionPerformed

        if (!alice.getText().isEmpty() || !bob.getText().isEmpty()) {
            DiffieHellman dh = new DiffieHellman(alice.getText(), bob.getText());
            DFKey.setText(dh.getSignature());
        } else {
            DFKey.setText("Mauvais arguments passés en paramètres");
        }
    }//GEN-LAST:event_generateDFKeyActionPerformed

    private void copyDFKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyDFKeyActionPerformed
        Toolkit toolKit = Toolkit.getDefaultToolkit();
        Clipboard cb = toolKit.getSystemClipboard();
        cb.setContents(new StringSelection(DFKey.getText()), null);
    }//GEN-LAST:event_copyDFKeyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiffieHellmanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiffieHellmanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiffieHellmanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiffieHellmanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DiffieHellmanGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea DFKey;
    private javax.swing.JTextField alice;
    private javax.swing.JTextField bob;
    private javax.swing.JButton copyDFKey;
    private javax.swing.JButton generateAlice;
    private javax.swing.JButton generateBob;
    private javax.swing.JButton generateDFKey;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JLabel labelB;
    // End of variables declaration//GEN-END:variables
}
