/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examples;

import java.io.BufferedReader;
import java.io.IOException;
import java.nio.charset.Charset;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

/**
 *
 * @author roman
 */
public class RSAGUI extends javax.swing.JFrame {

    /**
     * Creates new form RSAGUI
     */
    public RSAGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        texteACrypter = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        publicKeyRSA = new javax.swing.JTextArea();
        generationCleRsa = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        crypterRSA = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        texteCrypteRSA = new javax.swing.JTextArea();
        decrypterRSA = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        texteDecrypteRSA = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cryptage RSA");

        jLabel3.setText("Saisissez votre message :");

        texteACrypter.setAlignmentX(0.0F);
        texteACrypter.setName("texteACrypter"); // NOI18N
        texteACrypter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texteACrypterActionPerformed(evt);
            }
        });

        jLabel4.setText("Entrez la clé publique pour le cryptage :");

        publicKeyRSA.setColumns(20);
        publicKeyRSA.setLineWrap(true);
        publicKeyRSA.setRows(5);
        publicKeyRSA.setName("publicKeyRSA"); // NOI18N
        jScrollPane7.setViewportView(publicKeyRSA);

        generationCleRsa.setText("Générer vos clés RSA");
        generationCleRsa.setToolTipText("");
        generationCleRsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generationCleRsaActionPerformed(evt);
            }
        });

        jButton1.setText("Afficher vos clés RSA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        crypterRSA.setText("Crypter");
        crypterRSA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crypterRSAActionPerformed(evt);
            }
        });

        jLabel9.setText("Message crypté");

        texteCrypteRSA.setColumns(20);
        texteCrypteRSA.setRows(5);
        texteCrypteRSA.setName("texteCrypteRSA"); // NOI18N
        jScrollPane1.setViewportView(texteCrypteRSA);

        decrypterRSA.setText("Décrypter");
        decrypterRSA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decrypterRSAActionPerformed(evt);
            }
        });

        jLabel10.setText("Message décrypté");

        texteDecrypteRSA.setEditable(false);
        texteDecrypteRSA.setColumns(20);
        texteDecrypteRSA.setRows(5);
        jScrollPane3.setViewportView(texteDecrypteRSA);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(texteACrypter)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(104, 104, 104)
                                        .addComponent(crypterRSA))
                                    .addComponent(jScrollPane1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(decrypterRSA))
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(generationCleRsa, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(texteACrypter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(generationCleRsa)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(decrypterRSA)
                        .addComponent(crypterRSA))
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void texteACrypterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texteACrypterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texteACrypterActionPerformed

    private void generationCleRsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generationCleRsaActionPerformed
        RSA.generateKeys(512);
        //RSA rsa = new RSA();
        // rsa.generateKeys(512);
    }//GEN-LAST:event_generationCleRsaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Path publicKeyFile = Paths.get("rsa.pub");
        Charset charset = Charset.forName("UTF-8");
        try {
            BufferedReader br = Files.newBufferedReader(publicKeyFile, charset);
            String publicKey = br.readLine();
            br.close();
            RSAKeys rsaKeys = new RSAKeys();
            rsaKeys.setPublicKey(publicKey);
            rsaKeys.show();
        } catch (IOException ioe) {
            System.err.println("Error " + ioe);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void crypterRSAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crypterRSAActionPerformed
        String encryptedText = RSA.RSAEncrypt(texteACrypter.getText(), publicKeyRSA.getText());
        texteCrypteRSA.setText(encryptedText);
    }//GEN-LAST:event_crypterRSAActionPerformed

    private void decrypterRSAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decrypterRSAActionPerformed
        String decryptedText = RSA.RSADecrypt(texteCrypteRSA.getText());
        texteDecrypteRSA.setText(decryptedText);
    }//GEN-LAST:event_decrypterRSAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RSAGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RSAGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RSAGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RSAGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RSAGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton crypterRSA;
    private javax.swing.JButton decrypterRSA;
    private javax.swing.JButton generationCleRsa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextArea publicKeyRSA;
    private javax.swing.JTextField texteACrypter;
    private javax.swing.JTextArea texteCrypteRSA;
    private javax.swing.JTextArea texteDecrypteRSA;
    // End of variables declaration//GEN-END:variables
}
